name: Deploy

on:
  push:
    tags:
      - 'deploy*'  # triggers on tags starting with "deploy"

jobs:
  precommit:
    uses: ./.github/workflows/linter.yml

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Add your deploy steps below
    - name: Run deploy script
      run: |
        